//
// Apiv1wallettransactionTo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Apiv1wallettransactionTo: Codable {

    public var hours: Int64?
    public var address: String?
    public var coins: Int64?

    public init(hours: Int64?, address: String?, coins: Int64?) {
        self.hours = hours
        self.address = address
        self.coins = coins
    }


}

