//
// Apiv1walletsMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Apiv1walletsMeta: Codable {

    public var filename: String?
    public var encrypted: Bool?
    public var cryptoType: String?
    public var label: String?
    public var type: String?
    public var version: String?
    public var coin: String?
    public var timestamp: Int?

    public init(filename: String?, encrypted: Bool?, cryptoType: String?, label: String?, type: String?, version: String?, coin: String?, timestamp: Int?) {
        self.filename = filename
        self.encrypted = encrypted
        self.cryptoType = cryptoType
        self.label = label
        self.type = type
        self.version = version
        self.coin = coin
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey { 
        case filename
        case encrypted
        case cryptoType = "crypto_type"
        case label
        case type
        case version
        case coin
        case timestamp
    }


}

