//
// Apiv1walletsEntries.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Apiv1walletsEntries: Codable {

    public var publicKey: String?
    public var address: String?

    public init(publicKey: String?, address: String?) {
        self.publicKey = publicKey
        self.address = address
    }

    public enum CodingKeys: String, CodingKey { 
        case publicKey = "public_key"
        case address
    }


}

