//
// Apiv1exploreraddressStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Apiv1exploreraddressStatus: Codable {

    public var unconfirmed: Bool?
    public var blockSeq: Int64?
    public var label: Int64?
    public var confirmed: Bool?

    public init(unconfirmed: Bool?, blockSeq: Int64?, label: Int64?, confirmed: Bool?) {
        self.unconfirmed = unconfirmed
        self.blockSeq = blockSeq
        self.label = label
        self.confirmed = confirmed
    }

    public enum CodingKeys: String, CodingKey { 
        case unconfirmed
        case blockSeq = "block_seq"
        case label
        case confirmed
    }


}

