//
// Apiv1wallettransactionHoursSelection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Apiv1wallettransactionHoursSelection: Codable {

    public var mode: String?
    public var shareFactor: String?
    public var type: String?

    public init(mode: String?, shareFactor: String?, type: String?) {
        self.mode = mode
        self.shareFactor = shareFactor
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case mode
        case shareFactor = "share_factor"
        case type
    }


}

