//
// Apiv1wallettransactionWallet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Apiv1wallettransactionWallet: Codable {

    public var unspents: [String]?
    public var addresses: [String]?
    public var password: String?
    public var _id: String?

    public init(unspents: [String]?, addresses: [String]?, password: String?, _id: String?) {
        self.unspents = unspents
        self.addresses = addresses
        self.password = password
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case unspents
        case addresses
        case password
        case _id = "id"
    }


}

