//
// Apiv1exploreraddressInputs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Apiv1exploreraddressInputs: Codable {

    public var owner: String?
    public var hours: Int64?
    public var calculatedHours: Int64?
    public var coins: String?
    public var uxid: String?

    public init(owner: String?, hours: Int64?, calculatedHours: Int64?, coins: String?, uxid: String?) {
        self.owner = owner
        self.hours = hours
        self.calculatedHours = calculatedHours
        self.coins = coins
        self.uxid = uxid
    }

    public enum CodingKeys: String, CodingKey { 
        case owner
        case hours
        case calculatedHours = "calculated_hours"
        case coins
        case uxid
    }


}

