//
// Apiv1exploreraddressOutputs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Apiv1exploreraddressOutputs: Codable {

    public var hours: Int64?
    public var dst: String?
    public var coins: String?
    public var uxid: String?

    public init(hours: Int64?, dst: String?, coins: String?, uxid: String?) {
        self.hours = hours
        self.dst = dst
        self.coins = coins
        self.uxid = uxid
    }


}

