//
// InlineResponse2003.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2003: Codable {

    public enum State: String, Codable {
        case pending = "pending"
        case connected = "connected"
        case introduced = "introduced"
    }
    public var lastReceived: Int64?
    public var lastSent: Int64?
    public var outgoing: Bool?
    public var mirror: Int?
    public var address: String?
    public var listenPort: Int?
    public var isTrustedPeer: Bool?
    public var connectedAt: Int64?
    public var unconfirmedVerifyTransaction: InlineResponse2003UnconfirmedVerifyTransaction?
    public var _id: Int64?
    public var state: State?
    public var userAgent: String?
    public var height: Int64?

    public init(lastReceived: Int64?, lastSent: Int64?, outgoing: Bool?, mirror: Int?, address: String?, listenPort: Int?, isTrustedPeer: Bool?, connectedAt: Int64?, unconfirmedVerifyTransaction: InlineResponse2003UnconfirmedVerifyTransaction?, _id: Int64?, state: State?, userAgent: String?, height: Int64?) {
        self.lastReceived = lastReceived
        self.lastSent = lastSent
        self.outgoing = outgoing
        self.mirror = mirror
        self.address = address
        self.listenPort = listenPort
        self.isTrustedPeer = isTrustedPeer
        self.connectedAt = connectedAt
        self.unconfirmedVerifyTransaction = unconfirmedVerifyTransaction
        self._id = _id
        self.state = state
        self.userAgent = userAgent
        self.height = height
    }

    public enum CodingKeys: String, CodingKey { 
        case lastReceived = "last_received"
        case lastSent = "last_sent"
        case outgoing
        case mirror
        case address
        case listenPort = "listen_port"
        case isTrustedPeer = "is_trusted_peer"
        case connectedAt = "connected_at"
        case unconfirmedVerifyTransaction = "unconfirmed_verify_transaction"
        case _id = "id"
        case state
        case userAgent = "user_agent"
        case height
    }


}

