//
// InlineResponse2004.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2004: Codable {

    public var announced: String?
    public var isValid: Bool?
    public var checked: String?
    public var received: String?
    public var transaction: Apiv1pendingTxsTransaction?

    public init(announced: String?, isValid: Bool?, checked: String?, received: String?, transaction: Apiv1pendingTxsTransaction?) {
        self.announced = announced
        self.isValid = isValid
        self.checked = checked
        self.received = received
        self.transaction = transaction
    }

    public enum CodingKeys: String, CodingKey { 
        case announced
        case isValid = "is_valid"
        case checked
        case received
        case transaction
    }


}

