//
// InlineResponse2007.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2007: Codable {

    public var data: InlineResponse2007Data?
    public var error: Any?

    public init(data: InlineResponse2007Data?, error: Any?) {
        self.data = data
        self.error = error
    }


}

