//
// InlineResponse200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse200: Codable {

    public var hours: Int64?
    public var coins: Int?
    public var uxid: String?
    public var ownerAddress: String?
    public var spentBlockSeq: Int?
    public var spentTx: String?
    public var time: Int64?
    public var srcBlockSeq: Int64?
    public var srcTx: String?

    public init(hours: Int64?, coins: Int?, uxid: String?, ownerAddress: String?, spentBlockSeq: Int?, spentTx: String?, time: Int64?, srcBlockSeq: Int64?, srcTx: String?) {
        self.hours = hours
        self.coins = coins
        self.uxid = uxid
        self.ownerAddress = ownerAddress
        self.spentBlockSeq = spentBlockSeq
        self.spentTx = spentTx
        self.time = time
        self.srcBlockSeq = srcBlockSeq
        self.srcTx = srcTx
    }

    public enum CodingKeys: String, CodingKey { 
        case hours
        case coins
        case uxid
        case ownerAddress = "owner_address"
        case spentBlockSeq = "spent_block_seq"
        case spentTx = "spent_tx"
        case time
        case srcBlockSeq = "src_block_seq"
        case srcTx = "src_tx"
    }


}

