//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineObject: Codable {

    public var changeAddress: String?
    public var hoursSelection: Apiv1wallettransactionHoursSelection?
    public var ignoreUnconfirmed: Bool?
    public var to: [Apiv1wallettransactionTo]?
    public var wallet: Apiv1wallettransactionWallet?

    public init(changeAddress: String?, hoursSelection: Apiv1wallettransactionHoursSelection?, ignoreUnconfirmed: Bool?, to: [Apiv1wallettransactionTo]?, wallet: Apiv1wallettransactionWallet?) {
        self.changeAddress = changeAddress
        self.hoursSelection = hoursSelection
        self.ignoreUnconfirmed = ignoreUnconfirmed
        self.to = to
        self.wallet = wallet
    }

    public enum CodingKeys: String, CodingKey { 
        case changeAddress = "change_address"
        case hoursSelection = "hours_selection"
        case ignoreUnconfirmed = "ignore_unconfirmed"
        case to
        case wallet
    }


}

