//
// InlineResponse2003UnconfirmedVerifyTransaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Represent unconfirmed transactions */

public struct InlineResponse2003UnconfirmedVerifyTransaction: Codable {

    public var burnFactor: Int?
    public var maxTransactionSize: Int?
    public var maxDecimals: Int?

    public init(burnFactor: Int?, maxTransactionSize: Int?, maxDecimals: Int?) {
        self.burnFactor = burnFactor
        self.maxTransactionSize = maxTransactionSize
        self.maxDecimals = maxDecimals
    }

    public enum CodingKeys: String, CodingKey { 
        case burnFactor = "burn_factor"
        case maxTransactionSize = "max_transaction_size"
        case maxDecimals = "max_decimals"
    }


}

