//
// InlineResponse2007Data.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2007Data: Codable {

    public var version: Int64?

    public init(version: Int64?) {
        self.version = version
    }


}

