//
// InlineResponse2001.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2001: Codable {

    public var csrfToken: String?

    public init(csrfToken: String?) {
        self.csrfToken = csrfToken
    }

    public enum CodingKeys: String, CodingKey { 
        case csrfToken = "csrf_token"
    }


}

