//
// InlineResponse2006.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2006: Codable {

    public var address: String?

    public init(address: String?) {
        self.address = address
    }


}

