//
// InlineResponse2002.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2002: Codable {

    public var outputs: [Apiv1exploreraddressOutputs]?
    public var innerHash: String?
    public var inputs: [Apiv1exploreraddressInputs]?
    public var fee: Int?
    public var sigs: [String]?
    public var length: Int64?
    public var txid: String?
    public var type: Int?
    public var status: Apiv1exploreraddressStatus?
    public var timestamp: Int?

    public init(outputs: [Apiv1exploreraddressOutputs]?, innerHash: String?, inputs: [Apiv1exploreraddressInputs]?, fee: Int?, sigs: [String]?, length: Int64?, txid: String?, type: Int?, status: Apiv1exploreraddressStatus?, timestamp: Int?) {
        self.outputs = outputs
        self.innerHash = innerHash
        self.inputs = inputs
        self.fee = fee
        self.sigs = sigs
        self.length = length
        self.txid = txid
        self.type = type
        self.status = status
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey { 
        case outputs
        case innerHash = "inner_hash"
        case inputs
        case fee
        case sigs
        case length
        case txid
        case type
        case status
        case timestamp
    }


}

