//
// InlineResponse2005.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2005: Codable {

    public var entries: [Apiv1walletsEntries]?
    public var meta: Apiv1walletsMeta?

    public init(entries: [Apiv1walletsEntries]?, meta: Apiv1walletsMeta?) {
        self.entries = entries
        self.meta = meta
    }


}

